# CloudMeet Lite - Docker Swarm Stack для кластеризации
# Используйте: docker stack deploy -c stack-compose.yml cloudmeet

version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cloudmeet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cloudmeet_secret}
      POSTGRES_MULTIPLE_DATABASES: cloudmeet_auth,cloudmeet_conference
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Auth Service - сервис аутентификации
  auth-service:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/cloudmeet-auth-service:${IMAGE_TAG:-latest}
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-cloudmeet}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cloudmeet_secret}
      - POSTGRES_DB=cloudmeet_auth
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-key-change-in-production}
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
    networks:
      - backend-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Conference Service - сервис конференций
  conference-service:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/cloudmeet-conference-service:${IMAGE_TAG:-latest}
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-cloudmeet}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cloudmeet_secret}
      - POSTGRES_DB=cloudmeet_conference
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-key-change-in-production}
      - JWT_ALGORITHM=HS256
      - CACHE_TTL_SECONDS=300
    networks:
      - backend-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Gateway - API шлюз
  gateway:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/cloudmeet-gateway:${IMAGE_TAG:-latest}
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - CONFERENCE_SERVICE_URL=http://conference-service:8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-key-change-in-production}
      - JWT_ALGORITHM=HS256
    networks:
      - backend-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Frontend - веб-интерфейс
  frontend:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/cloudmeet-frontend:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    networks:
      - backend-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

# Тома для постоянного хранения
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# Overlay сеть для взаимодействия сервисов в кластере
networks:
  backend-network:
    driver: overlay
    attachable: true
